name: Build openwrt images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    
jobs:

  build:

    strategy:
      matrix:
        platform: ['x86-64', 'armsr-armv8']
      fail-fast: true

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - name: Read Openwrt version file
        id: get-openwrt-version
        run: echo "version=$(grep -o '^[^#]*' openwrt.version | tr -d '[:space:]')" >> $GITHUB_OUTPUT

      - name: Read packages list for router
        id: get-pkg-list
        run: echo "pkgs=$(grep -o '^[^#]*' packages_router | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          image: ${{ matrix.platform }}
          openwrt-version: ${{ steps.get-openwrt-version.outputs.version }}
          packages: ${{ steps.get-pkg-list.outputs.pkgs }}
          rootfs-size: 512

      - name: Store built packages
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform }}
          path: bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v7
      - name: Display structure of downloaded files
        run: ls -R
