name: Build openwrt images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write # Required for creating releases and uploading assets
    
jobs:

  build:

    strategy:
      matrix:
        platform: ['x86-64', 'armsr-armv8']
      fail-fast: true

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Read Openwrt version file
        id: get-openwrt-version
        run: echo "version=$(grep -o '^[^#]*' openwrt.version | tr -d '[:space:]')" >> $GITHUB_OUTPUT

      - name: Read packages list for router
        id: get-pkg-list
        run: echo "pkgs=$(grep -o '^[^#]*' packages_router | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - uses: kennethso168/openwrt-imagebuilder-action@a4a20ac1ced987ff442b5077bf8dd0589e89e906 # v7.0.1
        with:
          image: ${{ matrix.platform }}
          openwrt-version: ${{ steps.get-openwrt-version.outputs.version }}
          packages: ${{ steps.get-pkg-list.outputs.pkgs }}
          rootfs-size: 512

      - name: Store built packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: ${{ matrix.platform }}
          path: bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
      - name: Display structure of downloaded files
        run: ls -R
      - name: Remove files not that are not images
        run: rm */sha256sums */profiles.json */*.bom.cdx.json */*.manifest
      - name: Display resulting structure again
        run: ls -R
      - name: Get current timestamp
        id: get-timestamp
        run: echo "ts=$(date '+%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: build-${{ steps.get-timestamp.outputs.ts }}
          name: OpenWRT Build at ${{ steps.get-timestamp.outputs.ts }}
          draft: false
          prerelease: false
          files: |
            x86-64/*
            armsr-armv8/*
